const attendance = (req,res)=>{

    try {
        console.log("attendance");
    } catch (error) {
        console.log("error on during atendance " , error)
    }
}
export {attendance};
